# Copyright (c) 2012-2015 Sebastien Rombauts (sebastien.rombauts@gmail.com)

language: cpp

# compilers to add to build matrix
compiler:
  - gcc
  - clang

sudo: false

addons:
  apt:
    packages:
    - cppcheck

# scripts to run before build
before_script:
  - mkdir build
  - cd build
  - cmake -DSQLITECPP_BUILD_EXAMPLES=ON -DSQLITECPP_BUILD_TESTS=ON -DSQLITECPP_RUN_DOXYGEN=OFF ..

# build examples, and run tests (ie make & make test)
script:
  - cmake --build .
  - ctest --output-on-failure
